function scr_playerreset()
{
	if (instance_exists(obj_endlevelfade))
	    instance_destroy(obj_endlevelfade);

	if (instance_exists(obj_timesup))
	    instance_destroy(obj_timesup);

	global.seconds = 59;
	global.minutes = 1;
	obj_player.state = states.normal;
	obj_player.visible = true;
	obj_player.player_x = 240;
	obj_player.player_y = 434;
	room = hub_room1;
	ds_list_clear(global.saveroom);
	ds_list_clear(global.baddieroom);

	with (obj_player)
	{
	    alarm[0] = -1;
	    alarm[1] = -1;
	    alarm[3] = -1;
	    alarm[4] = -1;
	    alarm[5] = -1;
	    alarm[6] = -1;
	    alarm[7] = -1;
	    alarm[8] = -1;
	    alarm[9] = -1;
	    alarm[10] = -1;
	    grav = 0.5;
	    hsp = 0;
	    vsp = 0;
	    global.playerhealth = 5;
	    xscale = 1;
	    yscale = 1;
	    steppy = false;
	    movespeedmax = 5;
	    jumpstop = false;
	    start_running = 1;
	    visible = true;
	    global.panic = false;
	    turn = 0;
	    jumpAnim = true;
	    dashAnim = 1;
	    landAnim = false;
	    machslideAnim = false;
	    moveAnim = true;
	    stopAnim = true;
	    crouchslideAnim = true;
	    crouchAnim = true;
	    machhitAnim = false;
	    stompAnim = false;
	    inv_frames = false;
	    turning = 0;
	    hurtbounce = 0;
	    hurted = false;
	    autodash = false;
	    mach2 = 0;
	    input_buffer_jump = 8;
	    input_buffer_secondjump = 8;
	    input_buffer_highjump = 8;
	    targetRoom = Realtitlescreen;
	    flash = false;
	    global.key_inv = false;
	    global.shroomfollow = 0;
	    global.cheesefollow = 0;
	    global.tomatofollow = 0;
	    global.sausagefollow = 0;
	    global.pineapplefollow = 0;
	    global.keyget = false;
	    global.collect = 0;
	    global.ammo = 0;
	    global.treasure = false;
	    global.combo = 0;
	    global.combotime = 0;
	    global.pizzacoin = 0;
	    global.toppintotal = 1;
	    global.hit = 0;
	    in_water = 0;
	    key_particles = false;
	    barrel = false;
	    bounce = false;
	    a = 0;
	    idle = 0;
	    attacking = false;
	    slamming = false;
	    superslam = 0;
	    machpunchAnim = false;
	    punch = false;
	    machfreefall = 0;
	    shoot = true;
	    instakillmove = false;
	    windingAnim = false;
	    facestompAnim = false;
	    ladderbuffer = 0;
	    chainsaw = 50;
	    toomuchalarm1 = 0;
	    toomuchalarm2 = 0;
	    dashdust = 0;
	    throwforce = 0;
	    hurtsound = 0;
	    idleanim = false;
	    momemtum = false;
	    cutscene = false;
	    grabbing = false;
	    dir = xscale;
	    shotgunAnim = false;
	    goingdownslope = false;
	    goingupslope = false;
	    fallinganimation = 0;
	    bombpeptimer = 100;
	    slapbuffer = 0;
	    slaphand = 1;
	    suplexmove = false;
	    suplexhavetomash = 0;
	    timeuntilhpback = 300;
	    anger = 0;
	    angry = false;
	}
}